spring:
  datasource:
    url: jdbc:h2:mem:restyourmind
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  servlet:
    context-path: /api/restyourmind