spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
server:
  contextPath: /
  port: 9191